### ISSUE TITLE
error in training

### ISSUE THREAD

**Issue by joewale** [RetroCirce/HTS-Audio-Transformer#10]
Hi，RetroCirce

       I get the error when running the esc_50 script for training as follows. How to solved it ?

`
RuntimeError: upsample_bicubic2d_backward_out_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
Epoch 0:   0%|          | 0/65 [00:04<?, ?it/s]          
`

**Comment by RetroCirce** [comment]
Hi,

Please set this to be False:
https://github.com/RetroCirce/HTS-Audio-Transformer/blob/356521f5dbb1893082c449a4993977fd624905f0/main.py#L331

And search "deterministic" in the main.py, you can change them to be False.

I think the reason is probably that some packages are upgraded to unlock/lock some supports.
