### ISSUE TITLE
Different length audio input for infer mode

### ISSUE THREAD

**Issue by CaptainPrice12** [RetroCirce/HTS-Audio-Transformer#7]
Hi, thanks for the interesting work! 

I have a question about the infer mode in htsat.py. When training, the length of audio input will always be 10 seconds. When inference, the model needs to handle variable-length audio input which could be longer or shorter than 10 seconds, but for the infer mode in the htsat.py,        
```
 if infer_mode:
            # in infer mode. we need to handle different length audio input
            frame_num = x.shape[2]
            target_T = int(self.spec_size * self.freq_ratio)
            repeat_ratio = math.floor(target_T / frame_num)
            x = x.repeat(repeats=(1,1,repeat_ratio,1))
            x = self.reshape_wav2img(x) 
```
What if the length of input frame_num > target_T (should be 256x4=1024 here)? If so, repeat_ratio will be 0. So how does the model process the audio longer than 10 seconds for inference here?

**Comment by RetroCirce** [comment]
Hi,

Thank you for your question, it is possible to handle an audio sample that has more than 'target_T'.
Our method is to cut the audio sample into different slices, each of which has the length 'target_T'. 
For example, a 15-sec piece can be sliced as [0-10] and [5-15]. And of course you can control the overlapping.
Then we send these slices into HTS-AT and get the result just like the "voting".

We did not implement this code in this repo since audio samples in our exps are always less than 10sec. But we face this question when we try to use this model in other scenario, where I actually implement this code at:
https://github.com/LAION-AI/CLAP/blob/d2d5dae8ea8f1ee02ac40242418a36d1d567943a/src/open_clip/model.py#L484-L533

You can check it and adapt it into your code.

Best,
Ke

**Comment by CaptainPrice12** [comment]
Hi Ke, thanks for your quick reply! I have some other questions for HTS-AT. 

1. As the paper mentioned in Section 2.1.1, mel-spectrogram is split into patch windows, then patches are split inside each window. The implementation in the code actually reshapes the mel-spectrogram from a rectangle (1024x64) to a square ((1024/4)x(64x4)=256x256), following the setting of Swin-transformer for image classification with square inputs. 
I was wondering have you compared your patching method to another way that directly split non-overlapping patch without reshaping the mel-spectrogram to a square shape (I guess this patching method is also workable for swin-transformer)? By the way, I guess one of the reasons might be that reshaping the input to 256x256 can use the pre-trained Swin-T model on ImageNet. 

2. I am assuming that the training detail mentioned in section 3.11 in the paper is for training HTS-AT from scratch. Could you provide more training details about using pre-trained Swin-T/C24? 

Thank you!
